services:
  web:
    container_name: bubbl-client
    build:
      context: .
      dockerfile: Dockerfile
    # image: bubbl-client:latest   # ❌ remove this OR keep it and add pull_policy: build
    pull_policy: build             # ✅ ensures local build instead of pull
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    env_file:
      - .env
    restart: unless-stopped
    # Note: alpine images don't have curl by default; see Dockerfile below where we install it.
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 5s
      retries: 5
